// <auto-generated />
using Clone_PokeAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Clone_PokeAPI.Migrations
{
    [DbContext(typeof(PokemonDBContext))]
    [Migration("20230411201652_BudSeedDatasFix")]
    partial class BudSeedDatasFix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Clone_PokeAPI.Models.PokemonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "bulbasaur"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ivysaur"
                        },
                        new
                        {
                            Id = 3,
                            Name = "venusaur"
                        },
                        new
                        {
                            Id = 4,
                            Name = "charmander"
                        },
                        new
                        {
                            Id = 5,
                            Name = "charmeleon"
                        },
                        new
                        {
                            Id = 6,
                            Name = "charizard"
                        },
                        new
                        {
                            Id = 7,
                            Name = "squirtle"
                        },
                        new
                        {
                            Id = 8,
                            Name = "wartortle"
                        },
                        new
                        {
                            Id = 9,
                            Name = "blastoise"
                        },
                        new
                        {
                            Id = 10,
                            Name = "caterpie"
                        },
                        new
                        {
                            Id = 11,
                            Name = "metapod"
                        },
                        new
                        {
                            Id = 12,
                            Name = "butterfree"
                        },
                        new
                        {
                            Id = 13,
                            Name = "weedle"
                        },
                        new
                        {
                            Id = 14,
                            Name = "kakuna"
                        },
                        new
                        {
                            Id = 15,
                            Name = "beedrill"
                        },
                        new
                        {
                            Id = 16,
                            Name = "pidgey"
                        },
                        new
                        {
                            Id = 17,
                            Name = "pidgeotto"
                        },
                        new
                        {
                            Id = 18,
                            Name = "pidgeot"
                        },
                        new
                        {
                            Id = 19,
                            Name = "rattata"
                        },
                        new
                        {
                            Id = 20,
                            Name = "raticate"
                        });
                });

            modelBuilder.Entity("Clone_PokeAPI.Models.PokemonType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("PokemonModelId")
                        .HasColumnType("int");

                    b.Property<int>("TypeModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonModelId");

                    b.HasIndex("TypeModelId");

                    b.ToTable("PokemonType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PokemonModelId = 1,
                            TypeModelId = 1
                        },
                        new
                        {
                            Id = 2,
                            PokemonModelId = 1,
                            TypeModelId = 2
                        },
                        new
                        {
                            Id = 3,
                            PokemonModelId = 2,
                            TypeModelId = 1
                        },
                        new
                        {
                            Id = 4,
                            PokemonModelId = 2,
                            TypeModelId = 2
                        },
                        new
                        {
                            Id = 5,
                            PokemonModelId = 3,
                            TypeModelId = 1
                        },
                        new
                        {
                            Id = 6,
                            PokemonModelId = 3,
                            TypeModelId = 2
                        },
                        new
                        {
                            Id = 7,
                            PokemonModelId = 4,
                            TypeModelId = 3
                        },
                        new
                        {
                            Id = 8,
                            PokemonModelId = 5,
                            TypeModelId = 3
                        },
                        new
                        {
                            Id = 9,
                            PokemonModelId = 6,
                            TypeModelId = 3
                        },
                        new
                        {
                            Id = 10,
                            PokemonModelId = 6,
                            TypeModelId = 7
                        },
                        new
                        {
                            Id = 11,
                            PokemonModelId = 7,
                            TypeModelId = 4
                        },
                        new
                        {
                            Id = 26,
                            PokemonModelId = 8,
                            TypeModelId = 4
                        },
                        new
                        {
                            Id = 12,
                            PokemonModelId = 9,
                            TypeModelId = 4
                        },
                        new
                        {
                            Id = 13,
                            PokemonModelId = 10,
                            TypeModelId = 5
                        },
                        new
                        {
                            Id = 14,
                            PokemonModelId = 11,
                            TypeModelId = 5
                        },
                        new
                        {
                            Id = 15,
                            PokemonModelId = 12,
                            TypeModelId = 5
                        },
                        new
                        {
                            Id = 16,
                            PokemonModelId = 12,
                            TypeModelId = 7
                        },
                        new
                        {
                            Id = 17,
                            PokemonModelId = 13,
                            TypeModelId = 5
                        },
                        new
                        {
                            Id = 18,
                            PokemonModelId = 13,
                            TypeModelId = 2
                        },
                        new
                        {
                            Id = 19,
                            PokemonModelId = 14,
                            TypeModelId = 2
                        },
                        new
                        {
                            Id = 20,
                            PokemonModelId = 15,
                            TypeModelId = 2
                        },
                        new
                        {
                            Id = 21,
                            PokemonModelId = 16,
                            TypeModelId = 6
                        },
                        new
                        {
                            Id = 22,
                            PokemonModelId = 17,
                            TypeModelId = 6
                        },
                        new
                        {
                            Id = 23,
                            PokemonModelId = 18,
                            TypeModelId = 6
                        },
                        new
                        {
                            Id = 24,
                            PokemonModelId = 19,
                            TypeModelId = 6
                        },
                        new
                        {
                            Id = 25,
                            PokemonModelId = 20,
                            TypeModelId = 6
                        });
                });

            modelBuilder.Entity("Clone_PokeAPI.Models.SpritesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FrontDefault")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherFrontDefault")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonModelId")
                        .IsUnique();

                    b.ToTable("Sprites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/1.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/1.svg",
                            PokemonModelId = 1
                        },
                        new
                        {
                            Id = 2,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/2.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/2.svg",
                            PokemonModelId = 2
                        },
                        new
                        {
                            Id = 3,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/3.svg",
                            PokemonModelId = 3
                        },
                        new
                        {
                            Id = 4,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/4.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/4.svg",
                            PokemonModelId = 4
                        },
                        new
                        {
                            Id = 5,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/5.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/5.svg",
                            PokemonModelId = 5
                        },
                        new
                        {
                            Id = 6,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/6.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/6.svg",
                            PokemonModelId = 6
                        },
                        new
                        {
                            Id = 7,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/7.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/7.svg",
                            PokemonModelId = 7
                        },
                        new
                        {
                            Id = 8,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/8.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/8.svg",
                            PokemonModelId = 8
                        },
                        new
                        {
                            Id = 9,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/9.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/9.svg",
                            PokemonModelId = 9
                        },
                        new
                        {
                            Id = 10,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/10.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/10.svg",
                            PokemonModelId = 10
                        },
                        new
                        {
                            Id = 11,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/11.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/11.svg",
                            PokemonModelId = 11
                        },
                        new
                        {
                            Id = 12,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/12.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/12.svg",
                            PokemonModelId = 12
                        },
                        new
                        {
                            Id = 13,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/13.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/13.svg",
                            PokemonModelId = 13
                        },
                        new
                        {
                            Id = 14,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/14.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/14.svg",
                            PokemonModelId = 14
                        },
                        new
                        {
                            Id = 15,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/15.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/15.svg",
                            PokemonModelId = 15
                        },
                        new
                        {
                            Id = 16,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/16.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/16.svg",
                            PokemonModelId = 16
                        },
                        new
                        {
                            Id = 17,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/17.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/17.svg",
                            PokemonModelId = 17
                        },
                        new
                        {
                            Id = 18,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/18.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/18.svg",
                            PokemonModelId = 18
                        },
                        new
                        {
                            Id = 19,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/19.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/19.svg",
                            PokemonModelId = 19
                        },
                        new
                        {
                            Id = 20,
                            FrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/20.png",
                            OtherFrontDefault = "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/dream-world/20.svg",
                            PokemonModelId = 20
                        });
                });

            modelBuilder.Entity("Clone_PokeAPI.Models.StatsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BaseStat")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PokemonModelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PokemonModelId");

                    b.ToTable("Stats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseStat = 49,
                            Name = "hp",
                            PokemonModelId = 1
                        },
                        new
                        {
                            Id = 2,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 1
                        },
                        new
                        {
                            Id = 3,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 1
                        },
                        new
                        {
                            Id = 4,
                            BaseStat = 49,
                            Name = "special-attack",
                            PokemonModelId = 1
                        },
                        new
                        {
                            Id = 5,
                            BaseStat = 49,
                            Name = "special-defense",
                            PokemonModelId = 1
                        },
                        new
                        {
                            Id = 6,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 2
                        },
                        new
                        {
                            Id = 7,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 2
                        },
                        new
                        {
                            Id = 8,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 2
                        },
                        new
                        {
                            Id = 9,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 2
                        },
                        new
                        {
                            Id = 10,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 2
                        },
                        new
                        {
                            Id = 11,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 3
                        },
                        new
                        {
                            Id = 12,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 3
                        },
                        new
                        {
                            Id = 13,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 3
                        },
                        new
                        {
                            Id = 14,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 3
                        },
                        new
                        {
                            Id = 15,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 3
                        },
                        new
                        {
                            Id = 16,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 4
                        },
                        new
                        {
                            Id = 17,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 4
                        },
                        new
                        {
                            Id = 18,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 4
                        },
                        new
                        {
                            Id = 19,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 4
                        },
                        new
                        {
                            Id = 20,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 4
                        },
                        new
                        {
                            Id = 21,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 5
                        },
                        new
                        {
                            Id = 22,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 5
                        },
                        new
                        {
                            Id = 23,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 5
                        },
                        new
                        {
                            Id = 24,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 5
                        },
                        new
                        {
                            Id = 25,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 5
                        },
                        new
                        {
                            Id = 26,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 6
                        },
                        new
                        {
                            Id = 27,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 6
                        },
                        new
                        {
                            Id = 28,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 6
                        },
                        new
                        {
                            Id = 29,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 6
                        },
                        new
                        {
                            Id = 30,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 6
                        },
                        new
                        {
                            Id = 31,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 7
                        },
                        new
                        {
                            Id = 32,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 7
                        },
                        new
                        {
                            Id = 33,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 7
                        },
                        new
                        {
                            Id = 34,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 7
                        },
                        new
                        {
                            Id = 35,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 7
                        },
                        new
                        {
                            Id = 36,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 8
                        },
                        new
                        {
                            Id = 37,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 8
                        },
                        new
                        {
                            Id = 38,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 8
                        },
                        new
                        {
                            Id = 39,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 8
                        },
                        new
                        {
                            Id = 40,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 8
                        },
                        new
                        {
                            Id = 41,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 9
                        },
                        new
                        {
                            Id = 42,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 9
                        },
                        new
                        {
                            Id = 43,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 9
                        },
                        new
                        {
                            Id = 44,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 9
                        },
                        new
                        {
                            Id = 45,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 9
                        },
                        new
                        {
                            Id = 46,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 10
                        },
                        new
                        {
                            Id = 47,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 10
                        },
                        new
                        {
                            Id = 48,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 10
                        },
                        new
                        {
                            Id = 49,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 10
                        },
                        new
                        {
                            Id = 50,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 10
                        },
                        new
                        {
                            Id = 51,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 11
                        },
                        new
                        {
                            Id = 52,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 11
                        },
                        new
                        {
                            Id = 53,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 11
                        },
                        new
                        {
                            Id = 54,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 11
                        },
                        new
                        {
                            Id = 55,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 11
                        },
                        new
                        {
                            Id = 56,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 12
                        },
                        new
                        {
                            Id = 57,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 12
                        },
                        new
                        {
                            Id = 58,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 12
                        },
                        new
                        {
                            Id = 59,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 12
                        },
                        new
                        {
                            Id = 60,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 12
                        },
                        new
                        {
                            Id = 61,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 13
                        },
                        new
                        {
                            Id = 62,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 13
                        },
                        new
                        {
                            Id = 63,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 13
                        },
                        new
                        {
                            Id = 64,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 13
                        },
                        new
                        {
                            Id = 65,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 13
                        },
                        new
                        {
                            Id = 66,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 14
                        },
                        new
                        {
                            Id = 67,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 14
                        },
                        new
                        {
                            Id = 68,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 14
                        },
                        new
                        {
                            Id = 69,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 14
                        },
                        new
                        {
                            Id = 70,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 14
                        },
                        new
                        {
                            Id = 71,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 15
                        },
                        new
                        {
                            Id = 72,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 15
                        },
                        new
                        {
                            Id = 73,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 15
                        },
                        new
                        {
                            Id = 74,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 15
                        },
                        new
                        {
                            Id = 75,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 15
                        },
                        new
                        {
                            Id = 76,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 16
                        },
                        new
                        {
                            Id = 77,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 16
                        },
                        new
                        {
                            Id = 78,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 16
                        },
                        new
                        {
                            Id = 79,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 16
                        },
                        new
                        {
                            Id = 80,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 16
                        },
                        new
                        {
                            Id = 81,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 17
                        },
                        new
                        {
                            Id = 82,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 17
                        },
                        new
                        {
                            Id = 83,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 17
                        },
                        new
                        {
                            Id = 84,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 17
                        },
                        new
                        {
                            Id = 85,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 17
                        },
                        new
                        {
                            Id = 86,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 18
                        },
                        new
                        {
                            Id = 87,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 18
                        },
                        new
                        {
                            Id = 88,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 18
                        },
                        new
                        {
                            Id = 89,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 18
                        },
                        new
                        {
                            Id = 90,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 18
                        },
                        new
                        {
                            Id = 91,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 19
                        },
                        new
                        {
                            Id = 92,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 19
                        },
                        new
                        {
                            Id = 93,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 19
                        },
                        new
                        {
                            Id = 94,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 19
                        },
                        new
                        {
                            Id = 95,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 19
                        },
                        new
                        {
                            Id = 96,
                            BaseStat = 45,
                            Name = "hp",
                            PokemonModelId = 20
                        },
                        new
                        {
                            Id = 97,
                            BaseStat = 49,
                            Name = "attack",
                            PokemonModelId = 20
                        },
                        new
                        {
                            Id = 98,
                            BaseStat = 49,
                            Name = "defense",
                            PokemonModelId = 20
                        },
                        new
                        {
                            Id = 99,
                            BaseStat = 65,
                            Name = "special-attack",
                            PokemonModelId = 20
                        },
                        new
                        {
                            Id = 100,
                            BaseStat = 65,
                            Name = "special-defense",
                            PokemonModelId = 20
                        });
                });

            modelBuilder.Entity("Clone_PokeAPI.Models.TypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TypeName = "grass"
                        },
                        new
                        {
                            Id = 2,
                            TypeName = "poison"
                        },
                        new
                        {
                            Id = 3,
                            TypeName = "fire"
                        },
                        new
                        {
                            Id = 4,
                            TypeName = "water"
                        },
                        new
                        {
                            Id = 5,
                            TypeName = "bug"
                        },
                        new
                        {
                            Id = 6,
                            TypeName = "normal"
                        },
                        new
                        {
                            Id = 7,
                            TypeName = "flying"
                        },
                        new
                        {
                            Id = 8,
                            TypeName = "electric"
                        });
                });

            modelBuilder.Entity("PokemonModelTypeModel", b =>
                {
                    b.Property<int>("PokemonsId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("PokemonsId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("PokemonModelTypeModel");
                });

            modelBuilder.Entity("Clone_PokeAPI.Models.PokemonType", b =>
                {
                    b.HasOne("Clone_PokeAPI.Models.PokemonModel", "PokemonModel")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("PokemonModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clone_PokeAPI.Models.TypeModel", "TypeModel")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("TypeModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PokemonModel");

                    b.Navigation("TypeModel");
                });

            modelBuilder.Entity("Clone_PokeAPI.Models.SpritesModel", b =>
                {
                    b.HasOne("Clone_PokeAPI.Models.PokemonModel", "Pokemon")
                        .WithOne("Sprites")
                        .HasForeignKey("Clone_PokeAPI.Models.SpritesModel", "PokemonModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("Clone_PokeAPI.Models.StatsModel", b =>
                {
                    b.HasOne("Clone_PokeAPI.Models.PokemonModel", "Pokemon")
                        .WithMany("Stat")
                        .HasForeignKey("PokemonModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("PokemonModelTypeModel", b =>
                {
                    b.HasOne("Clone_PokeAPI.Models.PokemonModel", null)
                        .WithMany()
                        .HasForeignKey("PokemonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Clone_PokeAPI.Models.TypeModel", null)
                        .WithMany()
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Clone_PokeAPI.Models.PokemonModel", b =>
                {
                    b.Navigation("PokemonTypes");

                    b.Navigation("Sprites")
                        .IsRequired();

                    b.Navigation("Stat");
                });

            modelBuilder.Entity("Clone_PokeAPI.Models.TypeModel", b =>
                {
                    b.Navigation("PokemonTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
